### ISSUE TITLE
usage

### ISSUE THREAD

**Issue by jibanes** [komsit37/sublime-q#29]
I've installed sublime 3 on linux, with a kdb+ session running in the background with 5000/tcp open.
editing a file in "q output" mode works well, meaning that the syntax is highlighted properly.
Should I be in "q output" mode or "q/kdb" mode?
F1 searches something in google.
but that's where the magic ends, how do you add a connection, the documentation says Cmd + alt + q. On linux Cmd is bound to Ctrl+R but Ctrl+R alt+q doesn't seem to do anything useful.

note: I'm in vi/vintage mode.

**Comment by jibanes** [comment]
From the sublime console output:

```init localhost:5000
	chain 2 command q_out_popup...
Styled Popup: Parsing color scheme
Traceback (most recent call last):
  File "/opt/sublime_text_3/sublime_plugin.py", line 1082, in run_
    return self.run(edit, **args)
  File "/home/XXX/.config/sublime-text-3/Installed Packages/q KDB.sublime-package/q_chain.py", line 17, in run
  File "/home/XXX/.config/sublime-text-3/Installed Packages/q KDB.sublime-package/q_out_popup.py", line 81, in do
  File "/home/XXX/.config/sublime-text-3/Installed Packages/q KDB.sublime-package/q_out_popup.py", line 29, in do
  File "/home/XXX/.config/sublime-text-3/Packages/StyledPopup/st3/styled_popup.py", line 20, in show_popup
    style_sheet = manager.get_stylesheet(color_scheme)["content"]
  File "/home/XXX/.config/sublime-text-3/Packages/StyledPopup/st3/styled_popup.py", line 107, in get_stylesheet
    scheme_css = SchemeParser().run(color_scheme)
  File "/home/XXX/.config/sublime-text-3/Packages/StyledPopup/st3/styled_popup.py", line 159, in run
    scheme = self.read_scheme(content)
  File "/home/XXX/.config/sublime-text-3/Packages/StyledPopup/st3/styled_popup.py", line 173, in read_scheme
    return  readPlistFromBytes(scheme)
  File "./python3.3/plistlib.py", line 104, in readPlistFromBytes
  File "./python3.3/plistlib.py", line 76, in readPlist
  File "./python3.3/plistlib.py", line 378, in parse
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 0
init localhost:5000```

**Comment by jibanes** [comment]
And without the popup:

```
init localhost:5000
break chain because output is none```

**Comment by komsit37** [comment]
1. You **need** to use `q/kdb` mode. This should be a default mode if you open .q file. The shortcuts should work correctly in this mode.

2. Yes, seems the popup is broken. I think not many people are using them anyway. I will have a look later.

3. This log is probably normal
```
init localhost:5000
break chain because output is none
```

Bonus
* Linux keymap is defined here
https://github.com/komsit37/sublime-q/blob/master/sublime/Default%20(Linux).sublime-keymap#L14
You can change this by copying them to your user key binding (Preferences/Key Bindings in OSX, not sure for Linux)
* You can also open connection via menu (Tools/Sublime-q/Connect)
* All in all, I haven't tested this in Linux since I don't have one

**Comment by jibanes** [comment]
Thank you if you can look at #2 it'd be much appreciated.

**Comment by komsit37** [comment]
should be fixed in https://github.com/komsit37/sublime-q/releases/tag/1.2.1
